wordpress:
  ingress:
    ingressClassName: traefik
  persistence:
    enabled: true
    size: 5Gi
    storageClass: "local-path"

mariadb:
  primary:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "local-path"
