{{- if .Values.medusa.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "medusa.fullname" . }}-db
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
{{ toYaml .Values.medusa.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.medusa.persistence.size }}
{{- if .Values.medusa.persistence.storageClass }}
  storageClassName: {{ .Values.medusa.persistence.storageClass }}
{{- end }}
{{- end }}
